"""add events table

Revision ID: 32a24abc49f4
Revises: 0e49c8a3dd26
Create Date: 2026-09-13 14:50:57.217184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32a24abc49f4'
down_revision: Union[str, None] = '0e49c8a3dd26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.Enum('academic', 'career', 'social', 'sports', 'arts_culture', 'volunteering', 'workshop', 'food', 'other', name='eventcategory')), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cost_notes', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending_review', 'published', 'rejected', 'expired', name='eventstatus'), nullable=False),
    sa.Column('raw_source_id', sa.String(), nullable=True),
    sa.Column('dedup_hash', sa.String(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_dedup_hash'), 'events', ['dedup_hash'], unique=False)
    op.create_index('ix_events_search_vector', 'events', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index('ix_events_search_vector', table_name='events', postgresql_using='gin')
    op.drop_index(op.f('ix_events_dedup_hash'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
